name: Feature Request
description: Suggest an idea or enhancement for StikJIT
labels: [enhancement]
body:
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see in StikJIT
      placeholder: I'd like StikJIT to have... because it would help with...
    validations:
      required: true
  - type: textarea
    id: detailed-description
    attributes:
      label: Additional details
      description: Provide any additional details or examples
      placeholder: This feature could work by... and might look like...
    validations:
      required: false
